---
title: The Primal Now
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: primalnowblog@gmail.com
description: 'This is a collection of things I''ve learned on my day-to-day quest
  for a more conscious, mindful, spiritual, and successful, life.

'
baseurl: ''
url: http://blog.primalnow.com
twitter_username: PrimalNow
facebook_username: PrimalNow
instagram_username: PrimalNow
google_analytics: UA-94108730-1
markdown: kramdown
gems:
- jekyll-feed
- jemoji
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
permalink: "/:categories/:title"
excerpt_separator: "<!--more-->"
seo:
  lengths:
    title: 60
    description: 150
    descriptionmin: 130
